# Generated by Django 5.2.17 on 2026-08-13 17:53

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension(),
    ]
