# Generated by Django 5.2.17 on 2026-08-13 19:02

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ocr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('PROCESSED', 'Processado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
