# Generated by Django 5.2.17 on 2026-08-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_ocr', '0003_fix_embedding_dims_and_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='author',
        ),
    ]
